openapi: 3.0.1

info:
  title: Ghostwriter Kant
  description: |
    Using GPT-2, create a philosophical paper like Immanuel Kant.<br> 
    Just let him know how to get started.
  contact:
    name: dleunji
  version: "1.0"

servers:
  - url: https://kubecon-tabtab-ainize-team.endpoint.ainize.ai

paths:
  /gpt2:
    post:
      requestBody:
        required: true
        description: | 
          Specify a length of the text and set the start prompt for the text to be generated.
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                context:
                  type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad Request
        
        '429':
          description: Busy to server, please retry again.

        '500':
          description: Server side error